name: upsert_all_server
description: Starting point for a Serverpod module.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  serverpod: ^1.1.0

dependency_overrides:
  serverpod:
    path: /Users/tom/serverpod/packages/serverpod

dev_dependencies:
  lints: ^1.0.1
